SELECT SUM(G.SCORE) AS 'SCORE', E.EMP_NO, E.EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES AS E 
INNER JOIN HR_GRADE AS G ON E.EMP_NO = G.EMP_NO
WHERE YEAR = '2022'
GROUP BY E.EMP_NAME , E.EMP_NO
ORDER BY SCORE DESC
LIMIT 0,1 ;